trigger:
  - main  # Se activa con cambios en la rama main

pool:
  vmImage: 'Rocky-latest'  # Usamos una imagen de Linux para Terraform

variables:
  - group: gcp-credentials  # Grupo de variables para las credenciales de GCP
  - name: tf_version
    value: '1.5.7'  # Versión específica de Terraform
  - name: gcp_project_id
    value: '$(GCP_PROJECT_ID)'  # ID de tu proyecto de GCP
  - name: gcp_region
    value: 'us-central1'  # Cambia según tu región
  - name: environment
    value: 'dev'  # Entorno (dev/staging/prod)

stages:
- stage: Validate
  displayName: 'Validar configuración de Terraform'
  jobs:
  - job: Validate
    steps:
    - task: TerraformInstaller@1
      displayName: 'Instalar Terraform'
      inputs:
        terraformVersion: '$(tf_version)'

    - script: |
        echo "Inicializando Terraform con backend GCS..."
        terraform init
      displayName: 'Inicializar Terraform'
      workingDirectory: '$(System.DefaultWorkingDirectory)/ruta/a/tu/codigo'

    - task: TerraformTaskV4@4
      displayName: 'Validar configuración de Terraform'
      inputs:
        provider: 'gcp'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/ruta/a/tu/codigo'

- stage: Plan
  displayName: 'Plan de ejecución de Terraform'
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:
    - task: TerraformInstaller@1
      displayName: 'Instalar Terraform'
      inputs:
        terraformVersion: '$(tf_version)'

    - task: TerraformTaskV4@4
      displayName: 'Ejecutar terraform plan'
      inputs:
        provider: 'gcp'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/ruta/a/tu/codigo'
        environmentServiceNameGCP: '$(GCP_SERVICE_CONNECTION)'
        commandOptions: '-out=tfplan'

    - task: PublishBuildArtifacts@1
      displayName: 'Publicar plan de Terraform'
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)/ruta/a/tu/codigo/tfplan'
        artifactName: 'terraform-plan'

- stage: Apply
  displayName: 'Aplicar cambios en GCP'
  dependsOn: Plan
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  jobs:
  - deployment: Apply
    environment: 'gcp-$(environment)'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'terraform-plan'

          - task: TerraformInstaller@1
            displayName: 'Instalar Terraform'
            inputs:
              terraformVersion: '$(tf_version)'

          - task: TerraformTaskV4@4
            displayName: 'Aplicar cambios de Terraform'
            inputs:
              provider: 'gcp'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/ruta/a/tu/codigo'
              environmentServiceNameGCP: '$(GCP_SERVICE_CONNECTION)'
              commandOptions: 'tfplan'